export const CategoryData=[
    {
        value:"environment",
        text:"Környezet"
    },
    {
        value:"calendar",
        text:"Naptár"
    },
    {
        value:"human",
        text:"Ember"
    },
    {
        value:"health",
        text:"Egészség"
    },
    {
        value:"clothes",
        text:"Ruhák"
    },
    {
        value:"home",
        text:"Otthon"
    },
    {
        value:"computer",
        text:"Számítógép"
    },
    {
        value:"flora",
        text:"Növényvilág"
    },
    {
        value:"fauna",
        text:"Állatvilág"
    },
    {
        value:"foodstuffs",
        text:"Élelmiszerek"
    },
    {
        value:"fruits",
        text:"Gyümölcsök"
    },
    {
        value:"drinks",
        text:"Italok"
    },
    {
        value:"city",
        text:"Város"
    },
    {
        value:"traveling",
        text:"Utazás"
    },
    {
        value:"abroad",
        text:"Külföld"
    },
    {
        value:"sport",
        text:"Sport"
    },
    {
        value:"children's world",
        text:"Gyerekek világa"
    },
    {
        value:"art",
        text:"Művészet"
    },
    {
        value:"natural sciences",
        text:"Természet"
    },
    {
        value:"math",
        text:"Matematika"
    },
    {
        value:"activity",
        text:"Cselekvés"
    },
]